[package]
name = "audioware-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
audioware-types = { path = "../../types/audioware-types" }
syn = "2"
proc-macro2 = "1"
quote = "1"
darling = "0.20"
heck = "0.4"
