[package]
name = "audioware"
version = "0.1.0"
edition = "2021"
description = "CP2077 modding tool: allows to play any audio file, without replacement"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audioware-types = { path = "types/audioware-types" }
audioware-macros = { path = "macros/audioware-macros" }
anyhow = "1"
kira = "0.8.5"
lazy_static = "1.4.0"
red4ext-rs = { path = "../red4ext-rs/red4ext", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
retour = "0.3.1"
strum = "0.25.0"
strum_macros = "0.25.3"
widestring = "1.0.2"
winapi = { version = "0.3.9", features = ["libloaderapi"] }
memoffset = "0.9.0"
