[workspace]
members = ["audioware"]
resolver = "2"

[workspace.package]
version = "0.8.11"
edition = "2021"
rust-version = "1.77.2"

[profile.release]
lto = "thin"
strip = true
codegen-units = 1

[workspace.dependencies]

