[workspace]
members = ["audioware", "audioware-types", "audioware-macros"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

[workspace.dependencies]
anyhow = "1"
audioware-macros = { path = "audioware-macros" }
audioware-types = { path = "audioware-types" }
fixed-map = { version = "0.9.3", features = ["serde"] }
red4ext-rs = { git = "https://github.com/jac3km4/red4ext-rs.git", rev = "52ee3f3", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
strum = "0.25"
strum_macros = "0.25"
