[workspace]
members = ["audioware", "audioware-types", "audioware-macros"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[profile.release]
lto = "thin"

[workspace.dependencies]
anyhow = "1"
audioware-macros = { path = "audioware-macros" }
audioware-types = { path = "audioware-types" }
cxx = "1"
fixed-map = { version = "0.9.3", features = ["serde"] }
glam = { version = "0.25.0", features = ["mint"] }
# red4ext-rs = { git = "https://github.com/jac3km4/red4ext-rs.git", rev = "b9cff58", features = ["macros"] }
red4ext-rs = { path = "../red4ext-rs/red4ext", features = ["macros"] }
serde = { version = "1.0", features = ["derive"] }
static_assertions = "1.1.0"
strum = "0.25"
strum_macros = "0.25"
