[package]
name = "audioware"
version.workspace = true
edition.workspace = true
publish = false
description = "CP2077 modding tool: allows to play any audio file, without replacement"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audioware-core.workspace = true
audioware-bank.workspace = true
audioware-engine.workspace = true
audioware-macros.workspace = true
audioware-manifest.workspace = true
audioware-mem.workspace = true
audioware-sys.workspace = true
kira.workspace = true
once_cell.workspace = true
red4ext-rs.workspace = true
retour.workspace = true
