[package]
name = "audioware"
version.workspace = true
edition.workspace = true
publish = false
description = "CP2077 modding tool: allows to play any audio file, without replacement"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audioware-types.workspace = true
audioware-macros.workspace = true
anyhow.workspace = true
cxx.workspace = true
fixed-map.workspace = true
kira = "0.8.5"
lazy_static = "1.4.0"
memoffset = "0.9.0"
glam.workspace = true
red4ext-rs.workspace = true
retour = "0.3.1"
semver ={ version = "1", features = ["serde"] }
serde.workspace = true
serde_yaml = "0.9"
strum.workspace = true
strum_macros.workspace = true
ulid = "1.1.0"
validator = { version = "0.16", features = ["derive"] }
widestring = "1.0.2"
winapi = { version = "0.3.9", features = ["libloaderapi"] }
