[package]
name = "audioware"
version.workspace = true
edition.workspace = true
publish = false
description = "CP2077 modding tool: allows to play any audio file, without replacement"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
red4rs = { git = "https://github.com/jac3km4/red4rs.git", rev = "v0.1.7" }
red4rs-bindings = { git = "https://github.com/jac3km4/red4rs-bindings.git", rev = "v0.1.8" }
