[package]
name = "audioware"
version.workspace = true
edition.workspace = true
description = "CP2077 modding tool: allows to play any audio file, without replacement"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audioware-types.workspace = true
audioware-macros.workspace = true
anyhow = "1"
cxx = "1"
either = "1.9.0"
fixed-map = "0.9.3"
kira = "0.8.5"
lazy_static = "1.4.0"
music-timer = "0.1.6"
red4ext-rs.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
retour = "0.3.1"
semver ={ version = "1", features = ["serde"] }
strum = "0.25.0"
strum_macros = "0.25.3"
ulid = "1.1.0"
widestring = "1.0.2"
winapi = { version = "0.3.9", features = ["libloaderapi"] }
memoffset = "0.9.0"
