[package]
name = "audioware-macros"
version.workspace = true
edition.workspace = true
publish = false

[lib]
proc-macro = true

[dependencies]
audioware-mem.workspace = true
audioware-sys.workspace = true
syn = "2"
proc-macro2 = "1"
quote = "1"
