[package]
name = "audioware-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
either.workspace = true
kira.workspace = true
serde.workspace = true
snafu.workspace = true

[dev-dependencies]
test-case = "3.3"
